version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run: npm install
      - run:
          command: npm test
          working_directory: ./server
  build-and-push:
    machine: true
    steps:
      - checkout
      - run: 
         command: |
           docker build -t server:server server
           docker login -u kamilanowak -p testtestask
           docker push kamilanowak/server
workflows:
    final-build:
        jobs:
          - build-and-push:
              requires:
                 - build-and-test
              filters:
                branches:
                  only: master
          - build-and-test:
              filters:
                branches:
                  only: master

