version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run: npm install
      - run:
          command: npm test
          working_directory: ./server
      - run: docker build -t server:node-side-server server
      - run: docker push kamilanowak/node-side-server
workflows:
    build-and-test:
      jobs:
        - build-and-test:
              filters:
                branches:
                  only: master

