version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
 tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
 builds:
   machine: true
   steps:
     - checkout
     - run: 
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
workflows:
      build-on-master:
        jobs:
          - builds:
              requires:
                 - tests
              filters:
                branches:
                  only: master
          - tests:
              filters:
                branches:
                  only: master
