version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run: npm install
      - run:
          command: npm test
          working_directory: ./server
  build-and-push:
    steps:
      - checkout
      - run: 
         command: |
           docker build -t kamilanowak/server .
           echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
           docker push kamilanowak/server
workflows:
    build-and-test:
      jobs:
       - build-and-push:
         requires:
            - build-and-test         
        - build-and-test:
              filters:
                branches:
                  only: master

